minimumReleaseAge: 1440 # 1 day cooldown for new releases, see https://pnpm.io/settings#minimumreleaseage
nodeLinker: hoisted # see https://pnpm.io/settings#nodelinker
overrides:
  react-server-dom-webpack@=19.0: 19.0.3 # due to dependabot alerts
  domhandler: 5.0.3 # to fix tsc errors in ElementHandlers
patchedDependencies:
  xcode@3.0.1: patches/xcode+3.0.1.patch # see https://github.com/achorein/expo-share-intent?tab=readme-ov-file#installation
