// Auto-generated by scripts/sync-changelog.mjs — do not edit manually
const Changelog = {
  version: "2.2.0",
  versionCode: 2606111,
  notes:
    '- Artikel können jetzt vorgelesen werden\n- Lesezeit für Artikel wird angezeigt\n- Aktualisiertes Design für die Bildvorschau, Quellen und Erfolge\n- Suchseite neu gestaltet und aufgeteilt in Artikel- und KI-Fake-Suche\n- "Nach oben scrollen" auf der Startseite repariert\n- Performance-Verbesserungen und Fehlerbehebungen',
};

export default Changelog;
