// Auto-generated by scripts/prepare-changelog.mjs — do not edit manually
const Changelog = {
  version: "2.5.0",
  versionCode: 2607301,
  notes:
    "- Neu: Der Volksverpetzer-Podcast ist jetzt im Feed – Folgen direkt in der App anhören und später an der gehörten Stelle fortsetzen\n- Neu: Podcast-Folgen lassen sich öffnen, teilen und zu den Favoriten hinzufügen\n- Die Wiedergabe läuft jetzt weiter, während du in der App weiterliest\n- Artikelbilder werden jetzt über die volle Breite angezeigt\n- Der Teilen-Zähler zählt wieder korrekt\n- Fehlerbehebungen und Performance-Verbesserungen",
};

export default Changelog;
