name: Setup Node Pnpm and Expo
description: Composite action to install pnpm and optional setup node, pnpm install and expo setup
inputs:
  setup-node:
    description: "Setup Node (true/false)"
    required: false
    default: "true"
  install-deps:
    description: "Run pnpm install (true/false)"
    required: false
    default: "true"
  setup-expo-token:
    description: "Run expo setup (pass secret to set to true)"
    required: false
runs:
  using: composite
  steps:
    - name: 📦 Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10.33.0

    - name: 🏗 Setup Node
      if: ${{ inputs.setup-node == 'true' }}
      uses: actions/setup-node@v6
      with:
        node-version: "24"
        cache: "pnpm"

    - name: 🏗 Setup Expo and EAS
      if: ${{ inputs.setup-expo-token }}
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        packager: pnpm
        token: ${{ inputs.setup-expo-token }}

    - name: 📦 Install dependencies
      if: ${{ inputs.install-deps == 'true' }}
      run: pnpm install --frozen-lockfile
      shell: bash
